### ISSUE TITLE
where is the clustering

### ISSUE THREAD

**Issue by TaoStarlit** [HumamAlwassel/XDC#1]
thank you for your sharing. the pre-trained models would be useful for many researchers.  
In my view, the core of this repo the paper is the cross-modal deep CLUSTERING. However, I didn't find the code about the clustering yet.

**Comment by HumamAlwassel** [comment]
Hi Tao,

Thanks for your interest in our work.
This repo is meant for the pretrained model. Unfortunately, Facebook does not plan on releasing the training source code as it uses internal FB tools. However, we detail the full implementation details in our paper (please refer to the supplementary material). If you are interested in the clustering itself, then you can make use of the K-Means implementation in Scipy, since XDC does not innovate in the clustering algorithm itself. 

We hope that you find the pretrained models we have released useful for your application.

Cheers
